server:
  port: 8088
  servlet:
    context-path: /api/
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainingdb        
---
server:
  port: 8088
  servlet:
    context-path: /api/
  
spring:
  config:
    activate:
      on-profile:
      - docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: trainingdb